<?php
	/**
	 * assetr v0.1 <http://code.google.com/p/assetr/>
	 *
	 * Copyright 2008 Duane Jeffers
	 * This file is part of assetr.
	 *
	 * assetr is free software: you can redistribute it and/or modify
	 * it under the terms of the GNU General Public License as published by
	 * the Free Software Foundation, either version 3 of the License, or
	 * (at your option) any later version.
	 *
	 * assetr is distributed in the hope that it will be useful,
	 * but WITHOUT ANY WARRANTY; without even the implied warranty of
	 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	 * GNU General Public License for more details.
	 *
	 * You should have received a copy of the GNU General Public License
	 * along with assetr.  If not, see <http://www.gnu.org/licenses/>.
	 *
	 * What is this file?:
	 * display.functions.php - The Display functions are html snippets in php functions, used for easy UI writing.
	 **/

// start_page function - begins creating the page.
function start_page($dis_title) {
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <title>assetr v0.1 <? (empty($dis_title)) ? '' : print ":: $dis_title"; ?></title>
  <meta http-equiv="Content-Type" content="text/html; charset=iso8859-1" />
  <link href="css/assetr.css" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" type="text/css" href="css/yui/reset/reset.css"> 
  <link rel="stylesheet" type="text/css" href="css/yui/fonts/fonts.css"> 
  <link rel="stylesheet" type="text/css" href="css/yui/grids/grids.css"> 
  <link rel="stylesheet" type="text/css" href="css/yui/base/base.css"> <?
}

// dis_header_editarea function - inserts the javascript for EditArea.
function dis_header_editarea($asset_id, $script_type) {
?><script language="javascript" src="js/edit_area/edit_area_full.js"></script>
<script language="javascript">
editAreaLoader.init({
			id: "editarea"	// id of the textarea to transform	
			,start_highlight: true
			,font_size: "8"
			,allow_resize: "n"
			,allow_toggle: false
			,language: "en"
			,syntax: "<? print '$script_type'; ?>"	
			,toolbar: "save, |, search, go_to_line, |, undo, redo, |, change_smooth_selection, highlight, reset_highlight, |, help"
			,save_callback: ""
				
		});
</script><?
}
/*
<script language="javascript" src="js/edit_area/xmlhttp.js"></script>
function asset_save(id, content) {
	var postingdata = 'assetid=<? print "$asset_id"; ?>&content=' + content;
	var submit = new XMLHTTP("save_asset.php?");
	var xmlDoc = submit.call(postingdata, processReqChange);
}
*/

// dis_header_sh function - inserts the javascript for syntaxhighlighter
function dis_header_sh() {
?><link type="text/css" rel="stylesheet" href="css/SyntaxHighlighter.css" />
<script language="javascript" src="js/sh/shCore.js"></script>
<script language="javascript" src="js/sh/shBrushCss.js"></script>
<script language="javascript" src="js/sh/shBrushCpp.js"></script>
<script language="javascript" src="js/sh/shBrushCSharp.js"></script>
<script language="javascript" src="js/sh/shBrushDelphi.js"></script>
<script language="javascript" src="js/sh/shBrushJava.js"></script>
<script language="javascript" src="js/sh/shBrushJScript.js"></script>
<script language="javascript" src="js/sh/shBrushPhp.js"></script>
<script language="javascript" src="js/sh/shBrushPython.js"></script>
<script language="javascript" src="js/sh/shBrushRuby.js"></script>
<script language="javascript" src="js/sh/shBrushSql.js"></script>
<script language="javascript" src="js/sh/shBrushVb.js"></script>
<script language="javascript" src="js/sh/shBrushXml.js"></script>
<script language="javascript">
dp.SyntaxHighlighter.ClipboardSwf = 'js/sh/clipboard.swf';
dp.SyntaxHighlighter.HighlightAll('code');
</script><?
}

// dis_header function - finishs the HTML header as well as opens the main page. - Needs main assetr headerbar.
function dis_header($class="1") {
	echo "\n"; ?>
  </head>
  <body>
   <div id="doc" <? ($class !== "1") ? '' : print " class=\"yui-t1\""; ?>>
   <div id="hd">
   	<div id="logo"><img src="images/assetr-logo.png" alt="assetr Logo" /></div>
    <div id="logininfo"><strong>Logged in as:</strong> Duane</div>
   </div>
<?
}

//dis_footer function - ends the html page.
function dis_footer() {
	echo "\n"; ?>
  <div id="ft">
   <div id="copyright">Generated By <a href="http://code.google.com/p/assetr/">assetr</a>. assetr is &copy; 2008 <a href="http://www.duanejeffers.com/assetr">Duane Jeffers</a></div>
  </div>
  </div>
 </body>
</html>
<?
}

// dis_error function - outputs the error code.
function dis_error($error_msg) {
	echo "\n"; ?>
  <div id="error"><? print "$error_msg"; ?></div><?
}

// dis_code function - outputs preformatted code for SyntaxHighlighter to use.
function dis_code($code, $type) {
	echo "\n"; ?>
  <textarea name="code" class="<? print '$type'; ?>"><? echo "$code"; ?></textarea><?
}

// dis_code_edit function - outputs code for use with EditArea.
function dis_code_edit($code) {
	echo "\n"; ?>
  <textarea id="editarea" name="Code Edit" style="height: 500px; width: 500px;"><? echo "$code"; ?></textarea><?
}
// dis_login function - outputs the code for login purposes.
function dis_login($ret_page="main.php") {
	echo "\n"; ?>
   <div id="bd">
     <div id="loginform" align="center">
	<form action="checklogin.php" method="POST">
	<input type="hidden" name="return" value="<? print "$ret_page"; ?>" />
	<p>Username: <input type="text" name="username" /></p>
	<p>Password: <input type="password" name="password" /></p>
	</form>
    </div>
   </div>
<?
}

// dis_upload function - outputs the proper html code for the upload form.
function dis_upload() {

}

// dis_sidebar function - outputs the sidebar with the pre-formatted data.
function dis_sidebar($side_data) {

}

// dis_content function - outputs the main content area with the pre-formatted data.
function dis_content($content_data) {

}

?>
